# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'firebaseRepro' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebaseRepro

  pod 'Firebase/Core', '~> 5.20.1'
  pod 'Firebase/Auth', '~> 5.20.1'
  pod 'Firebase/Database', '~> 5.20.1'
  pod 'Firebase/Firestore', '~> 5.20.1'

  target 'firebaseReproTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'firebaseRepro-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for firebaseRepro-tvOS

  target 'firebaseRepro-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
